---
whitelist:
- MIT
- Apache 2.0
- ruby
- BSD
- ISC
- LGPL-3
- GPLv2
- LGPL
- Apache License 2.0
- LGPL-3.0
- Apache License Version 2.0
- 2-clause BSDL
- New BSD
ignore_groups:
#- test
#- development
dependencies_file_dir: './doc/'
project_name: # project name
